sudo: required
services:
  - docker
before_install:
  - docker build -t rajeshecb70/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rajeshecb70/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "docker"
  env: "docker-react-env"
  bucker_name: "elasticbeanstalk-us-east-1-590183919919"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
